FROM node:20-alpine AS builder

RUN apk add --no-cache python3 make g++ pkgconfig build-base linux-headers

WORKDIR /opt/app

COPY package.json yarn.lock ./
RUN yarn install

COPY . .
RUN yarn build && ls -la dist/

FROM node:20-alpine

WORKDIR /opt/app

COPY --from=builder /opt/app/dist ./dist
COPY --from=builder /opt/app/node_modules ./node_modules
COPY --from=builder /opt/app/package.json ./

USER node

EXPOSE 3000

CMD ["node", "dist/src/main"]
